
/* Drop Tables */

DROP TABLE IF EXISTS BC_TEAM_TASK_TAG_RELATION;
DROP TABLE IF EXISTS BC_TEAM_TASK;
DROP TABLE IF EXISTS BC_IDENTITY_ACTOR_HISTORY;
DROP TABLE IF EXISTS BC_TEAM_TASK_PRIORITY;
DROP TABLE IF EXISTS BC_TEAM_TASK_TAG;




/* Create Tables */

CREATE TABLE BC_IDENTITY_ACTOR_HISTORY
(
	ID INT NOT NULL,
	CONSTRAINT BCPK_IDENTITY_ACTOR_HISTORY PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE BC_TEAM_TASK
(
	ID INT NOT NULL,
	PID INT,
	STATUS_ INT NOT NULL,
	PRIORITY_ INT DEFAULT 0 NOT NULL,
	TITLE_ VARCHAR(255) NOT NULL,
	DEADLINE_ TIMESTAMP WITH TIME ZONE,
	AUTHOR_ INT NOT NULL,
	CREATE_TIME_ TIMESTAMP WITH TIME ZONE NOT NULL,
	DESC_ TEXT,
	CONSTRAINT BCPK_TEAM_TASK PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE BC_TEAM_TASK_PRIORITY
(
	ID INT NOT NULL,
	NAME_ VARCHAR(100) NOT NULL CONSTRAINT BCUK_TEAM_TASK_PRIORITY_NAME UNIQUE,
	VALUE_ INT DEFAULT 100 NOT NULL,
	CONSTRAINT BCPK_TEAM_TASK_PRIORITY PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE BC_TEAM_TASK_TAG
(
	ID INT NOT NULL,
	NAME_ VARCHAR(100) NOT NULL CONSTRAINT BCUK_TEAM_TASK_NAME UNIQUE,
	SN_ INT DEFAULT 0 NOT NULL,
	CONSTRAINT BCPK_TEAM_TASK_TAG PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE BC_TEAM_TASK_TAG_RELATION
(
	TASK_ INT NOT NULL,
	TAG_ INT NOT NULL,
	SN_ INT DEFAULT 0 NOT NULL,
	CONSTRAINT BCPK_TEAM_TASK_TAG_RELATION PRIMARY KEY (TASK_, TAG_)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE BC_TEAM_TASK
	ADD CONSTRAINT BCFK_TEAM_TASK_AUTHOR FOREIGN KEY (AUTHOR_)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BC_TEAM_TASK_TAG_RELATION
	ADD CONSTRAINT BCFK_TEAM_TASK_TYPE_RELATION_TASK FOREIGN KEY (TASK_)
	REFERENCES BC_TEAM_TASK (ID)
	ON UPDATE RESTRICT
	ON DELETE CASCADE
;


ALTER TABLE BC_TEAM_TASK
	ADD CONSTRAINT BCFK_TEAM_TASK_PRIORITY FOREIGN KEY (PRIORITY_)
	REFERENCES BC_TEAM_TASK_PRIORITY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BC_TEAM_TASK_TAG_RELATION
	ADD CONSTRAINT BCFK_TEAM_TASK_TYPE_RELATION_TYPE FOREIGN KEY (TAG_)
	REFERENCES BC_TEAM_TASK_TAG (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE BC_IDENTITY_ACTOR_HISTORY IS '参与者';
COMMENT ON COLUMN BC_IDENTITY_ACTOR_HISTORY.ID IS 'ID';
COMMENT ON TABLE BC_TEAM_TASK IS '任务';
COMMENT ON COLUMN BC_TEAM_TASK.ID IS 'ID';
COMMENT ON COLUMN BC_TEAM_TASK.PID IS '所属任务';
COMMENT ON COLUMN BC_TEAM_TASK.STATUS_ IS '状态 : 0-草稿,1-正常';
COMMENT ON COLUMN BC_TEAM_TASK.PRIORITY_ IS '优先级';
COMMENT ON COLUMN BC_TEAM_TASK.TITLE_ IS '标题';
COMMENT ON COLUMN BC_TEAM_TASK.DEADLINE_ IS '截止期限';
COMMENT ON COLUMN BC_TEAM_TASK.AUTHOR_ IS '创建人';
COMMENT ON COLUMN BC_TEAM_TASK.CREATE_TIME_ IS '创建时间';
COMMENT ON COLUMN BC_TEAM_TASK.DESC_ IS '描述';
COMMENT ON TABLE BC_TEAM_TASK_PRIORITY IS '优先级';
COMMENT ON COLUMN BC_TEAM_TASK_PRIORITY.ID IS 'ID';
COMMENT ON COLUMN BC_TEAM_TASK_PRIORITY.NAME_ IS '名称';
COMMENT ON COLUMN BC_TEAM_TASK_PRIORITY.VALUE_ IS '值 : 100代表一般(不设置优先级)';
COMMENT ON TABLE BC_TEAM_TASK_TAG IS '标签';
COMMENT ON COLUMN BC_TEAM_TASK_TAG.ID IS 'ID';
COMMENT ON COLUMN BC_TEAM_TASK_TAG.NAME_ IS '名称';
COMMENT ON COLUMN BC_TEAM_TASK_TAG.SN_ IS '序号';
COMMENT ON TABLE BC_TEAM_TASK_TAG_RELATION IS '任务与标签的关联';
COMMENT ON COLUMN BC_TEAM_TASK_TAG_RELATION.TASK_ IS '任务';
COMMENT ON COLUMN BC_TEAM_TASK_TAG_RELATION.TAG_ IS '类别';
COMMENT ON COLUMN BC_TEAM_TASK_TAG_RELATION.SN_ IS '序号';



